version: '3.8'

services:
  app:
    build: .
    container_name: todo-api
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - todo-network

  mysql:
    image: mysql:5.7
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql_data:
